name: Fullstack CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend:
    name: Backend - Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install
        working-directory: JWT_Backend

      - name: Run backend tests
        run: npm test || echo "No backend tests found"
        working-directory: JWT_Backend

  frontend:
    name: Frontend - Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:  
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./JWT_Authentication_Frontend

      - name: Run frontend tests
        run: npm test || echo "No frontend tests found"
        working-directory: ./JWT_Authentication_Frontend
